In [20]:
import numpy as np 

price = [2, 1, 10]
quantity_sold = [17, 40, 1]

price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
total_collected_array = price_array * quantity_sold_array
cost_array = np.array([0.25, 0.50, 5.00])
profit_array = price_array - cost_array
print(profit_array)
print(profit_array > 2.00)
price_array = np.append(price_array, 7)
print(price_array)
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

price_array = np.delete(price_array, -1)
print(price_array)

price_array[2] = 12
print(price_array)
baked_goods = ["brownie", "cookie", "cake", "pies", "fudge", 
               "cupcake", "banana bread"]
# Bakery Exercise (Core)
# baked_goods = ["brownie", "cookie" 39, "cake", "pies" 2, "fudge" 3, 
#               "cupcake" 16, "banana bread" 5]

# 2) Update the  quantity_sold_array to include the sale of 
#2 pies,  3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread.  
# You also realize that one of the cookies you thought was sold had actually
# fallen on the ground, so edit the quantity_sold_array from 40 to 39. 
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
quantity_sold_array[1] = 39
print(quantity_sold_array)

# 3) Determine the amount of money collected from the sale 
# of each item at the bake sale. 

total_collected_array = price_array * quantity_sold_array
print(total_collected_array)
full_price_total = 0
for money in total_collected_array:
  full_price_total += money
print(full_price_total)

# 4) Create a NumPy array "quantity_leftover" that includes the quantity of 
# each item remaining at the end of the sale: 
# 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread.  
#Hint: Make sure to include "0" for any item that was sold out. 
# Why is this important when creating the array?

quantity_leftover = np.array([0, 0, 2, 1, 6, 0, 2])
print(quantity_leftover)

# 5) The club decides to sell the leftover items at half price and everything 
# quickly sells out!  
# Determine how much money was collected from the clearance sale.

clearence_price = price_array * 0.5
total_collected_array = clearence_price * quantity_leftover
print(total_collected_array)
clearance_total = 0
for money in total_collected_array:
  clearance_total += money
print(clearance_total)

# 6) How much total money was collected from the bake sale 
# (including the sale of full price and clearance items)?
bake_sale_total = clearance_total + full_price_total
print(bake_sale_total)

[1.75 0.5  5.  ]
[False False  True]
[ 2  1 10  7]
[ 2.   1.  10.   7.   4.5  3.   4.   9. ]
[ 2.   1.  10.   7.   4.5  3.   4. ]
[ 2.   1.  12.   7.   4.5  3.   4. ]
[17 39  1  2  3 16  5]
[34.  39.  12.  14.  13.5 48.  20. ]
180.5
[0 0 2 1 6 0 2]
[ 0.   0.  12.   3.5 13.5  0.   4. ]
33.0
213.5
